/**
 * CEI3 Reminders — Renders deadlines from data/reminders.json
 * Generated by scripts/ingest.py from ingest/reminders.json
 */

const RemindersModule = (() => {
  let data = null;

  const TYPE_META = {
    homework: { icon: "📝", label: "Homework" },
    group: { icon: "👥", label: "Group Work" },
    exam: { icon: "📋", label: "Exam" },
    quiz: { icon: "❓", label: "Quiz" },
    project: { icon: "🔧", label: "Project" },
    admin: { icon: "🏫", label: "Admin" },
  };

  function getCountdown(dateStr) {
    const now = new Date();
    now.setHours(0, 0, 0, 0);
    const due = new Date(dateStr + "T23:59:59");
    const diff = Math.ceil((due - now) / (1000 * 60 * 60 * 24));

    if (diff < -7) return null; // skip: more than a week past due
    if (diff < 0)
      return {
        text: `${Math.abs(diff)}d ago`,
        cls: "overdue",
        group: "overdue",
      };
    if (diff === 0) return { text: "Due today", cls: "soon", group: "today" };
    if (diff === 1)
      return { text: "Due tomorrow", cls: "soon", group: "this-week" };
    if (diff === 2)
      return { text: "2 days left", cls: "soon", group: "this-week" };
    return { text: `${diff}d left`, cls: "safe", group: "later" };
  }

  function groupLabel(group) {
    if (group === "overdue") return "🚨 Overdue";
    if (group === "today") return "⚠️ Today";
    if (group === "this-week") return "📅 This Week";
    return "📆 Later";
  }

  async function load() {
    try {
      const resp = await fetch("data/reminders.json");
      if (!resp.ok) return;
      data = await resp.json();
    } catch (e) {
      console.warn("reminders.json not loaded:", e);
    }
  }

  function render() {
    const container = document.getElementById("reminders-list");
    if (!container) return;

    const all = (data?.reminders || [])
      .map((r) => ({ ...r, countdown: getCountdown(r.date) }))
      .filter((r) => r.countdown !== null);

    if (!all.length) {
      container.innerHTML = `
        <div class="empty-state">
          <p>No upcoming reminders.</p>
          <p class="hint">Add reminders in <code>ingest/reminders.json</code> then run <code>python scripts/ingest.py</code></p>
        </div>`;
      return;
    }

    // Group by period
    const groups = {};
    for (const r of all) {
      if (!groups[r.countdown.group]) groups[r.countdown.group] = [];
      groups[r.countdown.group].push(r);
    }

    const order = ["overdue", "today", "this-week", "later"];
    let html = "";

    for (const group of order) {
      if (!groups[group]) continue;
      html += `<div class="reminder-group">
        <h3 class="reminder-group-title">${groupLabel(group)}</h3>`;
      for (const r of groups[group]) {
        const meta = TYPE_META[r.type] || { icon: "📌", label: r.type };
        html += `
        <div class="reminder-item ${r.countdown.cls}${!r.course_code ? " general" : ""}">
          <div class="reminder-left">
            <span class="reminder-type" title="${meta.label}">${meta.icon}</span>
          </div>
          <div class="reminder-body">
            <div class="reminder-title">${esc(r.title)}</div>
            <div class="reminder-course">${r.course_code ? esc(r.course_code) + " " + esc(r.course_name || "") : esc(meta.label)}</div>
          </div>
          <div class="reminder-right">
            <span class="reminder-date">${r.date}</span>
            <span class="reminder-countdown ${r.countdown.cls}">${r.countdown.text}</span>
          </div>
        </div>`;
      }
      html += "</div>";
    }

    container.innerHTML = html;
  }

  function esc(s) {
    if (!s) return "";
    const div = document.createElement("div");
    div.textContent = s;
    return div.innerHTML;
  }

  return { load, render };
})();
